#!/bin/bash
#SBATCH --job-name="Li2SO4 T is 298 m is 3 run 2"
#SBATCH -n 32
#SBATCH -t 24:00:00
#SBATCH --mem-per-cpu=1G

module load 2022r2
module load openmpi

lmp=~/software/lammps/lammps2022/src/ # getting the correct run file location
srun $lmp/lmp_mpi < simulation.in # computing with n cpu cores.
wait

exit 0