#!/bin/bash
#SBATCH --job-name="preproccessing"
#SBATCH --exclusive
#SBATCH -p parallel-12
#SBATCH -n 12
#SBATCH -t 150:00:00
#SBATCH --mem-per-cpu=1G

lmp=~/software/lammps/lam*22/src/ # getting the correct run file location
mpirun $lmp/lmp_mpi < simulation_preprocessing.in # computing with n cpu cores.
wait

exit 0

