#!/bin/bash
#SBATCH --job-name="Li2SO4 T is 298 m is 3 run 4"
#SBATCH -p parallel-28
#SBATCH -n 28
#SBATCH --exclusive
#SBATCH --mem-per-cpu=1G
#SBATCH -t 4-00:00:00

lmp=~/software/lammps/lam*22/src/ # getting the correct run file location
mpirun $lmp/lmp_mpi < simulation.in # computing with n cpu cores.
wait

exit 0
